default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  database: production
